url: https://courses.stolley.co
baseurl: /wd/

timezone: America/Chicago

course:
  number: COM 330/530
  title: Standards-Based Web Design
  uid: wd
  tagline: >
    Theory and applied practice of mobile-first, responsive web design according to current open
    standards. An experimental online-only class.
  term: Spring 2020
  # Set `days: ""` (empty string) for weekly/asynchronous classes
  days: ""
  license:
    name: Creative Commons
    url: https://creativecommons.org/licenses/by/4.0/
  instructor:
    honorific: Dr.
    name: Karl Stolley
    title: Professor
    full_title: Associate Professor of Digital Writing & Rhetoric
    url: https://stolley.co/
    github: https://github.com/karlstolley/
    email: karl.stolley@gmail.com
    office_hours: >
      Office hours via Basecamp Chat or Pings on Tuesdays, 4pm to 5pm, or by appointment or chance.
      I’m always signed into Basecamp and closely monitor my notifications. Message or email any
      time—I make students a priority, and I will respond as soon as I am able.
  navigation:
    - label: Calendar
      href: "#this-week" # Stock for policies, projects.
      id: cal # read this into SCSS somehow?
    - label: Basecamp
      href: "https://3.basecamp.com/3058761/projects/15262139"
      id: bcp
    - label: ClickMeeting
      href: "https://stolley.clickmeeting.com/com-330-530-meeting"
      id: clm
    - label: Demos
      href: "https://github.com/wd-2020"
      id: dmo
    - label: Projects
      href: "projects/#current" # Stock for policies, projects.
      id: pro # read this into SCSS somehow?
    - label: Policies
      href: "policies/" # Stock for policies, projects.
      id: pol # read this into SCSS somehow?

collections_dir: syllabus

collections:
  weeks:
  projects:
  policies:
    # Rearrange the files listed here to change their order on the policies page.
    # To remove a section from the policies page, you *must* delete the file in the
    # /syllabus/_policies/ directory
    order:
      - description.md
      - goals.md
      - outcomes.md
      - objectives.md
      - books.md
      - materials.md
      - special-needs.md
      - participation.md
      - assignment-submission.md
      - late-work.md
      - grading-policy.md
      - grading-criteria.md
      - technology-policy.md
      - academic-integrity.md

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-open-course

exclude:
  - backstop_data
  - backstop.json
  - exe
  - lib
  - Rakefile
  - "*.gemspec"
